[package]
name = "sample-tokio"
version = "0.1.0"
edition = "2021"

[build-dependencies]
thunk-rs = { path="../thunk-rs" }

[features]

[dependencies]
tokio = { version = "1.40.0", features = ["rt-multi-thread", "net", "macros"] }
